apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: v1
kind: Pod
metadata:
  name: demo
  namespace: demo
spec:
  containers:
    - name: demo
      args:
        - while true; do echo -en '\n'; printf SERVICE_ADDRESS=$SERVICE_ADDRESS'\n'; sleep 30; done;
      command:
        - sh
        - -c
      image: busybox:1.28
      env:
        - name: SERVICE_ADDRESS
          value: "https://172.17.0.1:80"