apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: recovery
  region: us-east-1
  version: "1.29"
managedNodeGroups:
  - name: mynodegroup
    instanceType: m5.large
    desiredCapacity: 2
    minSize: 1
    maxSize: 5
    volumeSize: 20